import { Fonts } from '@/config/fonts';
import { createMarkdownTableStyles } from '@/utils/markdownTable';

type ThemeColors = {
  onSurface: string;
  primary: string;
};

export function createNativeMarkdownStyles(colors: ThemeColors, isDark: boolean, fontSize = 15) {
  const bodySize = fontSize;
  const tab = 20;
  return {
    body: {
      color: colors.onSurface,
      fontSize: bodySize,
      lineHeight: Math.round(bodySize * 1.62),
      fontFamily: Fonts.ui.regular,
      letterSpacing: -0.075,
      width: '100%',
    },
    paragraph: {
      fontFamily: Fonts.ui.regular,
      marginTop: 0,
      marginBottom: 4,
      marginLeft: 0,
      paddingLeft: tab,
      width: '100%',
      flexWrap: 'wrap' as const,
    },
    strong: { fontFamily: Fonts.ui.bold },
    glossary_term: {
      fontFamily: Fonts.ui.bold,
      color: isDark ? '#8FB39C' : '#5A8A6A',
    },
    em: { fontFamily: Fonts.ui.regular, fontStyle: 'italic' as const },
    link: { fontFamily: Fonts.ui.medium, color: colors.primary },
    heading1: {
      fontFamily: Fonts.ui.extraBold,
      fontSize: 24,
      marginTop: 4,
      marginBottom: 10,
      paddingLeft: 0,
      letterSpacing: -0.48,
      lineHeight: 30,
      width: '100%',
      flexWrap: 'wrap' as const,
    },
    heading2: {
      fontFamily: Fonts.ui.extraBold,
      fontSize: 19,
      marginTop: 18,
      marginBottom: 2,
      paddingTop: 0,
      paddingLeft: tab,
      borderTopWidth: 0,
      letterSpacing: -0.3,
      lineHeight: 26,
      width: '100%',
      flexWrap: 'wrap' as const,
    },
    heading3: {
      fontFamily: Fonts.ui.extraBold,
      fontSize: 16.5,
      marginTop: 14,
      marginBottom: 2,
      paddingTop: 0,
      paddingLeft: tab * 2,
      borderTopWidth: 0,
      lineHeight: 22,
      width: '100%',
      flexWrap: 'wrap' as const,
    },
    heading4: {
      fontFamily: Fonts.ui.extraBold,
      fontSize: 15.5,
      marginTop: 14,
      marginBottom: 4,
      paddingLeft: tab * 2,
      lineHeight: 21,
      width: '100%',
      flexWrap: 'wrap' as const,
    },
    heading5: {
      fontFamily: Fonts.ui.extraBold,
      fontSize: 15,
      marginTop: 12,
      marginBottom: 4,
      paddingLeft: tab * 2,
      lineHeight: 20,
      width: '100%',
      flexWrap: 'wrap' as const,
    },
    heading6: {
      fontFamily: Fonts.ui.extraBold,
      fontSize: 13.5,
      marginTop: 10,
      marginBottom: 4,
      paddingLeft: tab * 2,
      lineHeight: 18,
      letterSpacing: 0.04,
      width: '100%',
      flexWrap: 'wrap' as const,
    },
    bullet_list: {
      marginTop: 2,
      marginBottom: 8,
      paddingLeft: tab * 2,
    },
    ordered_list: {
      marginTop: 2,
      marginBottom: 8,
      paddingLeft: tab * 2,
    },
    list_item: {
      marginBottom: 3,
      flexDirection: 'row' as const,
      alignItems: 'flex-start' as const,
    },
    bullet_list_icon: {
      marginLeft: 0,
      marginRight: 10,
      marginTop: 1,
    },
    ordered_list_icon: {
      marginLeft: 0,
      marginRight: 8,
      marginTop: 1,
      minWidth: 18,
    },
    bullet_list_content: {
      flex: 1,
      flexShrink: 1,
      minWidth: 0,
    },
    ordered_list_content: {
      flex: 1,
      flexShrink: 1,
      minWidth: 0,
    },
    code_inline: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(26,47,35,0.06)',
      color: colors.primary,
      paddingHorizontal: 5,
      paddingVertical: 1,
      borderRadius: 4,
      fontSize: bodySize - 1.5,
      fontFamily: Fonts.ui.regular,
    },
    code_block: {
      backgroundColor: isDark ? '#18181b' : '#F4F4F5',
      color: colors.onSurface,
      padding: 12,
      borderRadius: 10,
      fontSize: bodySize - 1.5,
      fontFamily: Fonts.ui.regular,
      marginVertical: 6,
    },
    fence: {
      backgroundColor: isDark ? '#18181b' : '#F4F4F5',
      color: colors.onSurface,
      padding: 12,
      borderRadius: 10,
      fontSize: bodySize - 1.5,
      fontFamily: Fonts.ui.regular,
      marginVertical: 6,
    },
    blockquote: {
      backgroundColor: isDark ? 'rgba(143,179,156,0.1)' : 'rgba(90,138,106,0.06)',
      borderColor: isDark ? 'rgba(143,179,156,0.35)' : 'rgba(90,138,106,0.28)',
      borderWidth: 1,
      borderRadius: 8,
      paddingTop: 8,
      paddingBottom: 8,
      paddingLeft: 12,
      paddingRight: 12,
      marginLeft: tab,
      marginRight: 0,
      marginTop: 4,
      marginBottom: 6,
    },
    hr: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.12)' : 'rgba(26,47,35,0.1)',
      height: 1,
      marginVertical: 12,
    },
    ...createMarkdownTableStyles(isDark),
  };
}
