
export const EVENTS = {
  APP_SESSION_STARTED: 'app_session_started',
  APP_SESSION_ENDED: 'app_session_ended',

  AUTH_PAGE_VIEWED: 'auth_page_viewed',
  AUTH_MODE_SWITCHED: 'auth_mode_switched',
  SIGNUP_STARTED: 'signup_started',
  SIGNUP_COMPLETED: 'signup_completed',
  SIGNUP_FAILED: 'signup_failed',
  LOGIN_STARTED: 'login_started',
  LOGIN_COMPLETED: 'login_completed',
  LOGIN_FAILED: 'login_failed',
  LOGOUT: 'logout',
  PASSWORD_RESET_REQUESTED: 'password_reset_requested',
  PASSWORD_RESET_COMPLETED: 'password_reset_completed',
  PASSWORD_RESET_FAILED: 'password_reset_failed',
  EMAIL_VERIFICATION_SENT: 'email_verification_sent',
  EMAIL_VERIFICATION_COMPLETED: 'email_verification_completed',
  EMAIL_VERIFICATION_FAILED: 'email_verification_failed',
  EMAIL_VERIFICATION_RESENT: 'email_verification_resent',
  ONBOARDING_STEP_COMPLETED: 'onboarding_step_completed',
  ONBOARDING_COMPLETED: 'onboarding_completed',

  CTA_CLICKED: 'cta_clicked',
  LANDING_PAGE_VIEWED: 'landing_page_viewed',

  HOME_VIEWED: 'home_viewed',
  CREATE_OPTION_SELECTED: 'create_option_selected',
  CONTENT_UPLOAD_STARTED: 'content_upload_started',
  CONTENT_UPLOAD_SUCCEEDED: 'content_upload_succeeded',
  CONTENT_UPLOAD_FAILED: 'content_upload_failed',
  CONTENT_PROCESSING_COMPLETED: 'content_processing_completed',
  CONTENT_PROCESSING_FAILED: 'content_processing_failed',
  CONTENT_OPENED: 'content_opened',

  CONTENT_VIEWER_OPENED: 'content_viewer_opened',
  CONTENT_VIEWER_CLOSED: 'content_viewer_closed',
  NOTES_VIEW_STARTED: 'notes_view_started',
  NOTES_VIEW_ENDED: 'notes_view_ended',
  CARD_DECK_SESSION_STARTED: 'card_deck_session_started',
  CARD_DECK_SESSION_ENDED: 'card_deck_session_ended',
  QUIZ_STARTED: 'quiz_started',
  QUIZ_ENDED: 'quiz_ended',
  PODCAST_PLAY_STARTED: 'podcast_play_started',
  PODCAST_PLAY_ENDED: 'podcast_play_ended',
  AI_CHAT_SESSION_STARTED: 'ai_chat_session_started',
  AI_CHAT_SESSION_ENDED: 'ai_chat_session_ended',
  FLOWCHART_VIEW_STARTED: 'flowchart_view_started',
  FLOWCHART_VIEW_ENDED: 'flowchart_view_ended',
  CONTENT_TAB_OPENED: 'content_tab_opened',

  NOTES_EDITED: 'notes_edited',
  FLOWCHART_GENERATE_STARTED: 'flowchart_generate_started',
  FLOWCHART_GENERATE_COMPLETED: 'flowchart_generate_completed',
  FLOWCHART_GENERATE_FAILED: 'flowchart_generate_failed',
  AI_CHAT_MESSAGE_SENT: 'ai_chat_message_sent',
  PODCAST_GENERATE_STARTED: 'podcast_generate_started',
  PODCAST_GENERATE_COMPLETED: 'podcast_generate_completed',
  PODCAST_AUDIO_PLAYED: 'podcast_audio_played',
  PODCAST_AUDIO_PAUSED: 'podcast_audio_paused',

  CARD_DECK_GENERATE_STARTED: 'flashcard_generate_started',
  CARD_DECK_GENERATE_COMPLETED: 'flashcard_generate_completed',
  CARD_DECK_GENERATE_FAILED: 'flashcard_generate_failed',
  CARD_DECK_DECK_CREATED: 'card_deck_created',
  CARD_DECK_IMPORT_COMPLETED: 'card_deck_import_completed',
  CARD_DECK_SESSION_STARTED: 'card_deck_session_started',
  CARD_DECK_GRADED: 'flashcard_graded',
  CARD_DECK_SESSION_ENDED: 'card_deck_session_ended',
  CARD_DECK_QUICK_REVIEW_STARTED: 'flashcard_quick_review_started',
  CARD_DECK_QUICK_REVIEW_ENDED: 'flashcard_quick_review_ended',
  CARD_DECK_REEL_SESSION_STARTED: 'card_reel_session_started',
  CARD_DECK_REEL_SESSION_ENDED: 'card_reel_session_ended',

  QUIZ_SESSION_STARTED: 'quiz_session_started',
  QUIZ_ANSWER_SUBMITTED: 'quiz_answer_submitted',
  QUIZ_SESSION_COMPLETED: 'quiz_session_completed',
  QUIZ_SESSION_ABANDONED: 'quiz_session_abandoned',
  EXAM_TARGET_CREATED: 'exam_target_created',
  EXAM_PRACTICE_STARTED: 'exam_practice_started',
  EXAM_PRACTICE_COMPLETED: 'exam_practice_completed',

  COURSE_CREATED: 'course_created',
  CONTENT_ADDED_TO_COURSE: 'content_added_to_course',
  COURSE_OPENED: 'course_opened',

  FOCUS_SESSION_STARTED: 'focus_session_started',
  FOCUS_SESSION_PAUSED: 'focus_session_paused',
  FOCUS_SESSION_RESUMED: 'focus_session_resumed',
  FOCUS_SESSION_COMPLETED: 'focus_session_completed',
  FOCUS_POMODORO_COMPLETED: 'focus_pomodoro_completed',

  PAYWALL_HIT: 'paywall_hit',
  PAYWALL_DISMISSED: 'paywall_dismissed',
  SUBSCRIPTION_PAGE_VIEWED: 'subscription_page_viewed',
  SUBSCRIPTION_MANAGE_VIEWED: 'subscription_manage_viewed',
  SUBSCRIPTION_CANCELLED: 'subscription_cancelled',
  UPGRADE_CLICKED: 'upgrade_clicked',
  PAYMENT_INITIATED: 'payment_initiated',
  PAYMENT_COMPLETED: 'payment_completed',
  PAYMENT_CANCELLED: 'payment_cancelled',
  PAYMENT_FAILED: 'payment_failed',

  ACCOUNT_VIEWED: 'account_viewed',
  ACCOUNT_LANGUAGE_UPDATED: 'account_language_updated',
  ACCOUNT_DELETE_STARTED: 'account_delete_started',
  ACCOUNT_DELETE_COMPLETED: 'account_delete_completed',
  ACCOUNT_DELETE_FAILED: 'account_delete_failed',
} as const
